### ISSUE TITLE
请问数据库可以切换成 sqlite 吗

### ISSUE THREAD

**Issue by mcuking** [1166544/nuxt.js-nest.js-isomorphism#1]
请问数据库可以切换成 sqlite 吗

**Comment by 1166544** [comment]
Nest.js目前支持sql类关系型和非关系型DB，引用sqlite的话需要使用type-orm,http://typeorm.delightful.studio/interfaces/_driver_sqlite_sqliteconnectionoptions_.sqliteconnectionoptions.html

**Comment by mcuking** [comment]
感谢回复，我已经改好了，刚刚接触 nestjs，所有有些生疏。你的项目写的很棒，不过我这边需求比较简单，只是做一个离线包管理平台，所以没用你的项目，而是自己从零搭建了一个项目😊
